#samples named in the rootfile
samples = {   'diboson': {   'info': {   'color': 862L,
                               'label': 'VV',
                               'typ': 'bkg'},
                   'plot': True},
    'singlet': {   'info': {   'color': 616L,
                               'label': 't',
                               'typ': 'bkg'},
                   'plot': True},
    'tHW_hbb': {   'info': {   'color': 603L,
                               'label': 'tHW (SM)',
                               'typ': 'signal'},
                   'plot': True},
    'tHq_hbb': {   'info': {   'color': 606L,
                               'label': 'tHq (SM)',
                               'typ': 'signal'},
                   'plot': True},
    'ttH': {   'info': {   'color': 601L,
                           'label': 't#bar{t}+H',
                           'typ': 'signal'},
               'plot': True},
    'ttbarW': {   'info': {   'color': 590L,
                              'label': 't#bar{t}+W',
                              'typ': 'bkg'},
                  'plot': True},
    'ttbarZ': {   'info': {   'color': 432L,
                              'label': 't#bar{t}+Z',
                              'typ': 'bkg'},
                  'plot': True},
    'ttbb': {   'info': {   'color': 635L,
                            'label': 't#bar{t}+b#bar{b} (4FS)',
                            'typ': 'bkg'},
                'plot': True},
    'ttbb_5FS': {   'info': {   'color': 635L,
                                'label': 't#bar{t}+b#bar{b} (5FS)',
                                'typ': 'bkg'},
                    'plot': False},
    'ttcc': {   'info': {   'color': 633L,
                            'label': 't#bar{t}+c#bar{c}',
                            'typ': 'bkg'},
                'plot': True},
    'ttlf': {   'info': {   'color': 625L,
                            'label': 't#bar{t}+lf',
                            'typ': 'bkg'},
                'plot': True},
    'wjets': {   'info': {   'color': 409L,
                             'label': 'W+jets',
                             'typ': 'bkg'},
                 'plot': True},
    'zjets': {   'info': {   'color': 413L,
                             'label': 'Z+jets',
                             'typ': 'bkg'},
                 'plot': True},

    'dibosonCR': {   'info': {   'color': 418L,
                               'label': 'VV CR',
                               'typ': 'bkg'},
                   'plot': True},
    'singletCR': {   'info': {   'color': 418L,
                               'label': 't CR',
                               'typ': 'bkg'},
                   'plot': True},
    'ttbarWCR': {   'info': {   'color': 418L,
                              'label': 't#bar{t}+W CR',
                              'typ': 'bkg'},
                  'plot': True},
    'ttbarZCR': {   'info': {   'color': 418L,
                              'label': 't#bar{t}+Z CR',
                              'typ': 'bkg'},
                  'plot': True},
    'ttbbCR': {   'info': {   'color': 418L,
                            'label': 't#bar{t}+b#bar{b} (4FS) CR',
                            'typ': 'bkg'},
                'plot': True},
    'ttbb_5FSCR': {   'info': {   'color': 418L,
                                'label': 't#bar{t}+b#bar{b} (5FS) CR',
                                'typ': 'bkg'},
                    'plot': False},
    'ttccCR': {   'info': {   'color': 418L,
                            'label': 't#bar{t}+c#bar{c} CR',
                            'typ': 'bkg'},
                'plot': True},
    'ttlfCR': {   'info': {   'color': 418L,
                            'label': 't#bar{t}+lf CR',
                            'typ': 'bkg'},
                'plot': True},
    'wjetsCR': {   'info': {   'color': 418L,
                             'label': 'W+jets CR',
                             'typ': 'bkg'},
                 'plot': True},
    'zjetsCR': {   'info': {   'color': 418L,
                             'label': 'Z+jets',
                             'typ': 'bkg'},
                 'plot': True},
                 
    }

#combined samples
plottingsamples = {   'ttV': {   'addSamples': [   'ttbarZ',
                                 'ttbarW'],
               'color': 432L,
               'label': 't#bar{t}+V',
               'typ': 'bkg'},
    'vjets': {   'addSamples': [   'wjets',
                                   'zjets'],
                 'color': 18,
                 'label': 'V+jets',
                 'typ': 'bkg'}}

#systematics to be plotted
systematics = [   ]

# order of the stack processes, descending from top to bottom
sortedprocesses = [   'ttlf',
    'ttcc',
    'ttbb',
    'ttbb_5FS',
    'ttbb_4FS']

#options for the plotting style
plotoptions = {   'cmslabel': 'private Work',
    'data': 'data_obs',
    'datalabel': 'data',
    'logarithmic': False,
    'lumiLabel': '41.5',
    'nominalKey': '$PROCESS__$CHANNEL',
    'normalize': False,
    'ratio': '#frac{data}{MC Background}',
    'shape': False,
    'signalScaling': -1,
    'splitLegend': True,
    'statErrorband': True,
    'systematicKey': '$PROCESS__$CHANNEL__$SYSTEMATIC',
    # "combineflag" : "shapes_prefit"/"shapes_fit_s",
    # "signallabel" : "Signal"
}
    